const express = require('express');
const fetch = require('node-fetch');
const cors = require('cors');
const app = express();
const PORT = process.env.PORT || 3000;
app.use(cors());
app.get('/api/time', async (req, res) => { try { const r = await fetch('https://api.binance.com/api/v3/time'); const d = await r.json(); res.json(d); } catch (e) { res.status(500).json({e:'Failed'}); } });
app.get('/api/klines', async (req, res) => { const { symbol, interval, limit } = req.query; try { const u = `https://api.binance.com/api/v3/klines?symbol=${symbol}&interval=${interval}&limit=${limit}`; const r = await fetch(u); const d = await r.json(); res.json(d); } catch (e) { res.status(500).json({e:'Failed'}); } });
app.use(express.static('public'));
app.listen(PORT, () => { console.log(`Server is running on port ${PORT}`); });
